version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
  auth_service:
    build: ./auth_service
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/
  user_service:
    build: ./user_service
    ports:
      - '5001:5001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/
  jobbot_service:
    build: ./jobbot_service
    ports:
      - '5002:5002'  # Flask API for pause/cancel
    depends_on:
      - mongo
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M