apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobbot
  template:
    metadata:
      labels:
        app: jobbot
    spec:
      containers:
      - name: jobbot
        image: your-registry/jobbot_service:latest
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
        env:
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: jobbot-service
spec:
  selector:
    app: jobbot
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP