name: Build and Push Base Image
on:
  push:
    branches: [main]
    paths:
      - 'base_image/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and Push Base Image
      run: |
        docker build -t ghcr.io/your-username/base-jobbot:latest ./base_image
        docker push ghcr.io/your-username/base-jobbot:latest